version: 2
updates:
- package-ecosystem: npm
  directory: "/frontend"
  schedule:
    interval: weekly
    time: "10:00"
  open-pull-requests-limit: 10
- package-ecosystem: mix
  directory: "/"
  schedule:
    interval: weekly
    time: "10:00"
  open-pull-requests-limit: 10
