apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Alertas EC
  description: Sample service documentation repository
  annotations:
    github.com/project-slug: mijailr/alertas_ec
    backstage.io/techdocs-ref: github:https://github.com/mijailr/alertas.ec.git
spec:
  type: service
  lifecycle: production
  owner: guest
