site_name: 'mock-docs'
site_description: 'mock-docs site description'
repo_url: https://github.com/mijailr/alertas_ec

nav:
  - Home: index.md
  - SubDocs: '!include ./sub-docs/mkdocs.yml'

plugins:
  - techdocs-core
