name: Docker

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE: docker.pkg.github.com/mijailr/alertas.ec/alertas_ec
    steps:
    - name: Checkout repository
      uses: actions/checkout@v1
    - name: Login docker registry
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        docker login docker.pkg.github.com -u $GITHUB_ACTOR -p $GITHUB_TOKEN
    - name: Build docker image
      run: docker build . -t $IMAGE:latest -t $IMAGE:${GITHUB_REF:10}
    - name: Push docker image
      run: |
        docker push $IMAGE:latest
        docker push $IMAGE:${GITHUB_REF:10}

