name: Elixir CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:alpine
        ports:
          - 5432:5432
    steps:
    - name: Checkout repository
      uses: actions/checkout@v1
    - name: Get deps cache
      uses: actions/cache@v1
      with:
        path: deps/
        key: ${{ runner.os }}-deps-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-deps-
    - name: Setup elixir
      uses: actions/setup-elixir@v1
      with:
        elixir-version: 1.10.2
        otp-version: 22.2
    - name: Install Dependencies
      run: mix deps.get
    - name: Run Tests
      run: mix test
    - name: Build release
      env:
        MIX_ENV: prod
      run: mix release
    - uses: actions/upload-artifact@v1
      with:
        name: alertas-ec-release
        path: _build/dev/rel/production

